export const SET_EMAIL = 'SET_EMAIL';
export const SET_NAME = 'SET_NAME';
export const TOGGLE_SUBSCRIPTION = 'TOGGLE_SUBSCRIPTION';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const SET_VERIFICATION_CODE = 'SET_VERIFICATION_CODE';
export const SET_COUNTRY_CODE = 'SET_COUNTRY_CODE';